### ISSUE TITLE
Line intersect detection fails sometimes

### ISSUE THREAD

**Issue by nouyang** [JuliaGeometry/GeometryTypes.jl#115]
There seems to be a bug in the line intersect code.

A specific failure case is 

``` 
using GeometryTypes
l = LineSegment(Point(6.0,11), Point(12.0,11))

r1 = GeometryTypes.LineSegment( Point(9.0,10.0), Point(9.0, 13.0))
r2 = GeometryTypes.LineSegment( Point(9.34365, 10.890), Point(9.34365, 13.402))
```

```
julia> intersects(l, r1)
(true, [9.0, 11.0])

julia> intersects(l, r2)
(false, [0.0, 0.0])
```
I would expect that the second case would return true as well.

**Comment by SimonDanisch** [comment]
That's a fair expectation :P Not sure where the error is... The [line](https://github.com/JuliaGeometry/GeometryTypes.jl/blob/master/src/lines.jl#L43) that failes the intersection test basically compares 9.3436 with 9.3436... Maybe I messed up coordinates somewhere.

**Comment by SimonDanisch** [comment]
The difference in the points seems to be large enough for this not to be a precision problem.

**Comment by visr** [comment]
Is `eps(Float64)` too small? This is what is happening with these segments:
```julia
x = 9.343649999999998
xmin = 9.34365
x < xmin - eps(Float64)  # -> true (current behavior)
x < prevfloat(xmin)  # -> false
prevfloat(xmin) == xmin - eps(xmin)  # -> true
```
Don't know much about these floating point issues, so not sure if `prevfloat` is the correct choice here.
Perhaps it makes more sense to copy the `isapprox` default `rtol`, e.g.
```julia
x < xmin - sqrt(eps(Float64))  # -> false
```

**Comment by SimonDanisch** [comment]
Ah great, guess I looked to hastily at the issue. I guess we should indeed just use `isapprox` directly!

**Comment by SimonDanisch** [comment]
@nouyang thanks for the issue, @visr thanks for taking a closer look and providing a solution! 
Should be fixed in: https://github.com/JuliaGeometry/GeometryTypes.jl/compare/sd/intersect?expand=1
