### ISSUE TITLE
Exact commands to use GLVisualize?

### ISSUE THREAD

**Issue by nouyang** [JuliaGeometry/GeometryTypes.jl#121]
Hello,
The README.md says "Some of the types offered by GeometryTypes visualized with GLVisualize"

Would it be possible to see the exact commands (or at least an example) of how the images were rendered?

Thanks!

**Comment by edljk** [comment]
[Makie.jl](https://github.com/SimonDanisch/Makie.jl) (which calls GLVisualize) is perhaps easier to learn. See the following example for ploting a sphere

```julia
using Makie, GeometryTypes
scene = Scene(resolution = (500, 500))
MakiE.mesh(Sphere(Point3f0(0), 1f0))
center!(scene)
```
Other examples can be found [here](https://gist.github.com/SimonDanisch/8f5489cffaf6b89c9a3712ba3eb12a84) (just replace `MakiE` by `Makie` :-)).

**Comment by SimonDanisch** [comment]
```Julia
using GLVisualize, GeometryTypes
prim = ... # the code from the example
_view(visualize(prim))
```
I had to do `GLNormalMesh(prim)` for the 3D primitives, but that just might be because I'm on a weird Makie refactor GLVisualize branch ;)
