### ISSUE TITLE
StaticArrays wants to deprecate FixedSizeArrays compatibility layer

### ISSUE THREAD

**Issue by andyferris** [JuliaGeometry/GeometryTypes.jl#132]
Heads up - I was thinking that Julia v0.7 might be a good time to add a deprecation to the `StaticArrays.FixedSizeArrays` module, for removal in Julia v1.0.

I noticed this package still uses that module. See https://github.com/JuliaArrays/StaticArrays.jl/issues/459

**Comment by SimonDanisch** [comment]
uhm, we could move it to geometrytypes, i guess ;) not sure how much work it would be to get rid of it for good^^

**Comment by andyferris** [comment]
Sure, I mean `Point` sounds like it could be the first GeometryType from which all other GeometryTypes are born :)

I'm not sure what "for good" means in this contect but for reasons (such as Geodesy.jl) it might be helpful to have the alias `AbstractPoint{N, T <: Real} = StaticArray{N, T}` (I.e. points are just static arrays of `Real`s). Just an idea.

In any case... it would be smoothest if we remove the reference to the FixedSizeArrays module in this repo before we deprecate it from StaticArrays.

**Comment by rdeits** [comment]
Are there other significant usages of FixedSizeArrays in the wild outside of the GeometryTypes ecosystem? If not, then I think it would be fine to just copy the FixedSizeArrays compatibility layer into GeometryTypes, which would be mostly non-breaking. Then StaticArrays could deprecate and remove its implementation as needed and GeometryTypes can migrate on its own schedule.
