### ISSUE TITLE
HomogenousMesh(::Sphere) generates flipped faces and NaNs

### ISSUE THREAD

**Issue by sjkelly** [JuliaGeometry/GeometryTypes.jl#16]
All hail the ominous sphere. I am working on this one.

![screenshot from 2015-10-15 19 42 22](https://cloud.githubusercontent.com/assets/2086412/10530346/f6a895ec-7374-11e5-8649-c89d648d4141.png)

**Comment by SimonDanisch** [comment]
Is this fixed?
