### ISSUE TITLE
requirements for  ASTInterpreter2

### ISSUE THREAD

**Issue by maxMel1** [JuliaGeometry/GeometryTypes.jl#168]
ERROR: Unsatisfiable requirements detected for package ASTInterpreter2 [e6d88f4b]:
 Problem with adding GeometryTypes:

ASTInterpreter2 [e6d88f4b] log:
 ├─possible versions are: 0.1.0-0.1.1 or uninstalled
 ├─restricted by compatibility requirements with Atom [c52e3926] to versions: 0.1.0-0.1.1
 │ └─Atom [c52e3926] log:
 │   ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.6, 0.5.0-0.5.10, 0.6.0-0.6.17, 0.7.0-0.7.15, 0.8.0-0.8.2] or uninstalled
 │   └─restricted to versions 0.7.8 by an explicit requirement, leaving only versions 0.7.8
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

using:
Windows 10 64bit
julia 1.01 ; client 0.8.1
atom 1.35.1 x64

**Comment by SimonDanisch** [comment]
This happens if you add any package with Pkg, if your package manager is in an inconsistent state - so this isn't related to GeometryTypes!
As a matter of fact, I also run into this and it was a bit annoying to fix... Try something like this:
```
pkg> rm Atom # important to not put them in the same command
pkg> rm Debugger
pkg> ASTInterpreter2
pkg> gc; up; add Atom
```
