### ISSUE TITLE
Export names from FixedSizeArrays?

### ISSUE THREAD

**Issue by sjkelly** [JuliaGeometry/GeometryTypes.jl#17]
It seems like some FixedSizeArray exports are re-exported by this package. I don't think this is
necessarily a problem now, but it might be in the future if we want to change vector backends.

CC @SimonDanisch

**Comment by SimonDanisch** [comment]
I think they belong to GeometryTypes API and if we switch the vector backends, we should make sure that we still export the same types? Are what are you referring to?
