### ISSUE TITLE
OffsetInteger operations incorrect

### ISSUE THREAD

**Issue by goretkin** [JuliaGeometry/GeometryTypes.jl#186]
I think the intent of `OffsetInteger` is that it preserves all the structure of integers, but the definitions at

https://github.com/JuliaGeometry/GeometryTypes.jl/blob/c42a2b336ac0e8135f71f4c0a48f3766ce5127e2/src/faces.jl#L26-L35

don't do this.

The operations shouldn't happen on the underlying value, but on the "effective" value.

**Comment by SimonDanisch** [comment]
Hm good point... I will see if there are any regression by fixing this!

**Comment by goretkin** [comment]
Thanks for looking at the PR!
