### ISSUE TITLE
Generalized Decomposition Algorithm

### ISSUE THREAD

**Issue by sjkelly** [JuliaGeometry/GeometryTypes.jl#20]
In f89d867e6c7b40e719886425a98b54d8f6dd5c63 I generalized the N-Face (N >=3) conversion, but it occurs to me that this can be generalized further. For example it should be possible to get all `Face{2}` from a `Face{3}`.

I propose the following syntax via `call` overloads of `NTuple`:
```
f = Face{3,Int,0}(1,2,3)
line_segments = NTuple{Face{2,Int,0}}(f)
```
This feels like an abuse of notation since the `NTuple` call does not have a determinate number.

**Comment by SimonDanisch** [comment]
Does this actually support `Face{N1} --> Face{N2}`?
Will leaving out N confuse the compiler? The generated function qiute likely makes this type stable regardless...

**Comment by sjkelly** [comment]
Can you give an example? I am not quite sure what you are referencing. The code generated in #21 is pretty good, but for triangulation it has a few `jne`s in the assembly which I am trying to track down.

**Comment by SimonDanisch** [comment]
I was just thinking out loud ;) I must admit, it wasn't really a helpful comment!
What version are not optimal? `@code_llvm triangulate(Face{3, Int, 0}, Face{4,Int,0}(1,2,3,4))` looks pretty great to me!

**Comment by sjkelly** [comment]
Thinking out load is encouraged! 
Here is the difference:
```
julia> @code_native Tuple{Face{2,Int,0}}(Face{4, Int, 0}(1,2,3,4))
	.text
Filename: /home/steve/.julia/v0.4/GeometryTypes/src/faces.jl
Source line: 20
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 20
	movq	16(%rdx), %rcx
	movq	24(%rdx), %rsi
	movq	(%rdx), %rax
	movq	8(%rdx), %rdx
	movq	%rax, 56(%rdi)
	movq	%rsi, 48(%rdi)
	movq	%rsi, 40(%rdi)
	movq	%rcx, 32(%rdi)
	movq	%rcx, 24(%rdi)
	movq	%rdx, 16(%rdi)
	movq	%rdx, 8(%rdi)
	movq	%rax, (%rdi)
	movq	%rdi, %rax
	popq	%rbp
	ret

julia> @code_native triangulate(GLTriangle, Face{4, Int, 0}(1,2,3,4))
	.text
Filename: /home/steve/.julia/v0.4/GeometryTypes/src/faces.jl
Source line: 6
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 6
	movq	(%rdx), %rax
	decq	%rax
	movl	%eax, %ecx
	cmpq	%rax, %rcx
	jne	L99
	movq	8(%rdx), %r8
	decq	%r8
	movl	%r8d, %esi
	cmpq	%r8, %rsi
	jne	L99
	movq	16(%rdx), %rsi
	decq	%rsi
	movl	%esi, %ecx
	cmpq	%rsi, %rcx
	jne	L99
	movq	24(%rdx), %rdx
	decq	%rdx
	movl	%edx, %ecx
	cmpq	%rdx, %rcx
	jne	L99
	movl	%edx, 20(%rdi)
	movl	%esi, 16(%rdi)
	movl	%eax, 12(%rdi)
	movl	%esi, 8(%rdi)
	movl	%r8d, 4(%rdi)
	movl	%eax, (%rdi)
	movq	%rdi, %rax
	popq	%rbp
	ret
L99:	movabsq	$jl_inexact_exception, %rax
	movq	(%rax), %rdi
	movabsq	$jl_throw_with_superfluous_argument, %rax
	movl	$6, %esi
	callq	*%rax
```

**Comment by SimonDanisch** [comment]
Well I guess that's what happens when you convert to an `UInt`....

**Comment by sjkelly** [comment]
It is actually because of `GLTriangle` requiting conversions. Here it is with no conversions:
```
julia> @code_native triangulate(Face{3,Int,0}, Face{4, Int, 0}(1,2,3,4))
	.text
Filename: /home/steve/.julia/v0.4/GeometryTypes/src/faces.jl
Source line: 6
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 6
	movq	(%rdx), %rax
	movq	8(%rdx), %rcx
	movq	16(%rdx), %rsi
	movq	24(%rdx), %rdx
	movq	%rdx, 40(%rdi)
	movq	%rsi, 32(%rdi)
	movq	%rax, 24(%rdi)
	movq	%rsi, 16(%rdi)
	movq	%rcx, 8(%rdi)
	movq	%rax, (%rdi)
	movq	%rdi, %rax
	popq	%rbp
	ret
```

**Comment by sjkelly** [comment]
> Well I guess that's what happens when you convert to an `UInt`....

Ha! Missed your answer by a refresh :P
