### ISSUE TITLE
Infinite recursive loop

### ISSUE THREAD

**Issue by blegat** [JuliaGeometry/GeometryTypes.jl#45]
I get a StackOverflowError with the following code using Julia v0.5

    julia> using GeometryTypes
    julia> large_sphere = HyperSphere(Point3f0(0), 1f0)
    GeometryTypes.HyperSphere{3,Float32}(FixedSizeArrays.Point{3,Float32}((0.0f0,0.0f0,0.0f0)),1.0f0)
    julia> decompose(Point3f0, large_sphere)
    ERROR: StackOverflowError:
     in decompose at /home/blegat/.julia/v0.5/GeometryTypes/src/decompose.jl:5 (repeats 26665 times)

This is taken from this example: http://simondanisch.github.io/lines/linesegments3d/

**Comment by SimonDanisch** [comment]
You might need to be on `sd/boundingboxes`, PR #44.
I think I should just merge it. @sjkelly what do you think?

**Comment by SimonDanisch** [comment]
I just saw, you have that from the prototypical documentation. This is for the `GLVisualize/next2` branch, which should be merged really soon!

**Comment by blegat** [comment]
It seems fixed by b2825ca :)
