### ISSUE TITLE
Coordinate system for meshes constructed from SignedDistanceField

### ISSUE THREAD

**Issue by rdeits** [JuliaGeometry/GeometryTypes.jl#49]
I've been playing with the meshing algorithms implemented in the `Meshes.jl` family, and they've been extremely helpful! But I noticed that the vertices of the meshes returned by marching cubes and marching tetrahedra are in an odd choice of coordinate system. As far as I can tell, the vertex coordinates are in the range [1, size(sdf)], mapping to the world-coordinate `bounds` of the field. While I can certainly undo that mapping to get world coordinates out, it seems like a somewhat strange choice. 

Since the SignedDistanceField stores its world-coordinate bounds, it would be possible to have the meshing algorithms return world coordinate vertices, which seems to me to impose less burden on the user. 

First, is this behavior intentional? Or is it a bug? If it's a bug, I'm happy to try to fix it.

For reference, the code I'm running to observe this behavior is:

``` julia
using Meshes
using GeometryTypes

s = SignedDistanceField(HyperRectangle(Vec(0,0,0.),Vec(1,1,1.))) do v
           sqrt(sum(dot(v,v))) - 1 # sphere
       end
m = HomogenousMesh(s) # uses Marching Tetrahedra from Meshing.jl
vertices(m)
```

```
973-element Array{FixedSizeArrays.Point{3,Float64},1}:
 Point(6.0,9.0,4.289259971769505)                              
 Point(10.759636704703446,1.759636704703446,3.0)               
 Point(6.0,8.0,6.093133249283693)                              
 Point(6.0,8.782712686772829,4.782712686772829)   
...
```

**Comment by twadleigh** [comment]
Assuming the values live at the vertices of the unit lattice is a convention of the marching tetrahedra algorithm as I implemented it.

That can easily be hidden from the user with knowledge of the right transformation.

**Comment by sjkelly** [comment]
@rdeits Thank you for the bug report! This is probably best filed under Meshing.jl since that is where all the "Meshing" algorithms live. I have fixed this for meshing with marching cubes, but I still need to do it for marching tetrahedra. I am currently refactoring the API to allow for multiple algorithms and I will include this fix.

**Comment by rdeits** [comment]
No problem, and thanks for the fix :). Want me to open an issue under Meshing.jl for this so it's around for future reference?
