### ISSUE TITLE
Clarify fields used in primitives.

### ISSUE THREAD

**Issue by rohitvarkey** [JuliaGeometry/GeometryTypes.jl#5]
Hey Simon, 

Would you mind telling me exactly what the fields are supposed to be in the [Cube](https://github.com/JuliaGeometry/GeometryTypes.jl/blob/master/src/types.jl#L53) and the [Pyramid](https://github.com/JuliaGeometry/GeometryTypes.jl/blob/master/src/types.jl#L78) primitives? I just want to make sure I'm setting them correctly in Compose3D.

Regards,
Rohit.

**Comment by SimonDanisch** [comment]
Oh sorry, totally forgot to answer this.

Here you go:
![image](https://cloud.githubusercontent.com/assets/1010467/8610830/9ecce45e-2685-11e5-860a-a14d37c34f84.png)
