### ISSUE TITLE
Integrate HyperRectangles

### ISSUE THREAD

**Issue by sjkelly** [JuliaGeometry/GeometryTypes.jl#6]
Would people find this useful? We could just bring it under a submodule for now: 

https://github.com/JuliaGeometry/HyperRectangles.jl

I was going to publish it to METADATA, but I think coordinating efforts would be best at this point.

cc: @KristofferC @SimonDanisch @rohitvarkey

**Comment by SimonDanisch** [comment]
Definitely nice! Probably it will make more sense when we have Vec{N, T}, though ;)
I'm still trying to wrap my mind around on how to compose 2D and 3D boundinboxes....
This will definitely be the first step!

**Comment by sjkelly** [comment]
I am reopening this so we can sort out the remaining details. After #7.
