### ISSUE TITLE
More flexible Simplex type?

### ISSUE THREAD

**Issue by jw3126** [JuliaGeometry/GeometryTypes.jl#60]
Currently the Simplex type has the number of vertices hard coded into its type. Which is perfect for many performance critical situations. But not for all, in some cases, one wants to have a Simplex and iteratively change the number of vertices. This comes up in quite some optimization problems, [gjk](https://en.wikipedia.org/wiki/Gilbert%E2%80%93Johnson%E2%80%93Keerthi_distance_algorithm) being the one that bothers me at the moment.

In such situations, a Simplex type with hard coded number of vertices leads to type instability. 
So I was wondering if a Simplex type with mutable number of vertices fits into the scope of this package, or if it is better done elsewhere. Same applies to a "convex hull of finitely many points" type.

**Comment by SimonDanisch** [comment]
If you make a PR, I'd be happy to include it :)
