### ISSUE TITLE
Plans to move to StaticArrays?

### ISSUE THREAD

**Issue by jw3126** [JuliaGeometry/GeometryTypes.jl#66]
Since [FixedSizeArrays will get replaced by StaticArrays](https://github.com/SimonDanisch/FixedSizeArrays.jl/issues/159) are there plans to port GeometryTypes.jl to StaticArrays?

**Comment by SimonDanisch** [comment]
Sorry, I moved this quite low on my current priority list.
Although, I tried lately to make a quick move, but noticed that StaticArrays doesn't allow me to inherit from it to create new types. Am I overlooking something, @andyferris?

**Comment by andyferris** [comment]
Hmm? It should be easy to inherit from `StaticArray`. What issues are you having, Simon? (You must define size on the type and a constructor that accepts a tuple).

**Comment by andyferris** [comment]
If you look at the files in *StaticArraays* which introduce new types you should get a good idea. For instance see `Point` in the `FixedSizeArrays` submodule to *StaticArrays*.

**Comment by SimonDanisch** [comment]
Lol.... okay very good, I thought it was possible :) Not sure in what state of mind I revoked that and decided that it wasn't possible :P

**Comment by andyferris** [comment]
Ok you had me worried that something was broken :). Carry on.

**Comment by SimonDanisch** [comment]
will be fixed on tag: https://github.com/JuliaLang/METADATA.jl/pull/9608
