### ISSUE TITLE
Enhanced GJK implementation

### ISSUE THREAD

**Issue by rdeits** [JuliaGeometry/GeometryTypes.jl#69]
I just wanted to let you know that I've been working on an implementation of EnhancedGJK (Cameron's improved version of GJK which uses pre-computed neighbors of mesh vertices to improve performance for repeated calls on the same pair of geometries with slightly different poses): https://github.com/rdeits/EnhancedGJK.jl

I'm using GeometryTypes under the hood, but have had to encapsulate the functions from GeometryTypes rather than extending them because I need slightly different behavior (and because I'm using StaticArrays internally).

However, as a part of that project, I've implemented Johnson's distance subalgorithm, the procedure for computing the vertex weights for the GJK simplex (equivalent to what `GeometryTypes.proj_sqdist` does. I've found that Johnson's algorithm is much faster (less than 100 nanoseconds for a 3-dimensional simplex, compared to several hundred nanoseconds for the implementation in GeometryTypes which uses the pseudoinverse). It also has the benefit of producing a valid (but non-unique) solution when the simplex is not linearly independent, whereas the pseudoinverse method returns NaNs. I think it might be possible to port the algorithm into GeometryTypes to replace the current `proj_sqdist` implementation. Would you be interested in that?

**Comment by SimonDanisch** [comment]
Of course, sounds good!
By the way, I'm very open to change behavior and we also want to move to StaticArrays very soon!

**Comment by rdeits** [comment]
Ok, that's great. Long-term, do you think having the implementation live inside GeometryTypes is better? Or should GeometryTypes be restricted to just describing the types, with the GJK behavior implemented in another package?

**Comment by SimonDanisch** [comment]
That's a good question! I'm no fan of monster packages, so if it has a well defined scope, put it rather in another package?

**Comment by rdeits** [comment]
Ok, sounds good. I'll keep hacking away at [rdeits/EnhancedGJK.jl](https://github.com/rdeits/EnhancedGJK.jl) for now, then, and let you know how it progresses.
