### ISSUE TITLE
Invalid subtyping in definition of AbstractMesh

### ISSUE THREAD

**Issue by blegat** [JuliaGeometry/GeometryTypes.jl#77]
In Julia v0.6, there is the following error in precompilation
```
ERROR: LoadError: LoadError: invalid subtyping in definition of AbstractMesh
Stacktrace:
(...)
while loading /home/travis/.julia/v0.6/GeometryTypes/src/types.jl, in expression starting on line 9
```
This line is:
```julia
abstract AbstractMesh{VertT, FaceT} <: AbstractGeometry
```
The errors seems to be that `AbstractGeometry` has the parameters `{N, T}` an now in Julia v0.6, you cannot subtype a type without specifying all parameters.

**Comment by SimonDanisch** [comment]
Yes, GeometryTypes does currently not support 0.6 :(

**Comment by Benoit9** [comment]
Does GLVisualize run on 0.6 without GeometryTypes? I tought 0.6 was required by CUDAnative, which is required by one of your examples?

**Comment by SimonDanisch** [comment]
It was at some point! haven't tested recently. But a lot of issues have piled up which have higher priority right now...
Also 0.6 has a bug which doesn't let me move on with one of my packages: https://github.com/JuliaLang/julia/issues/20103
And then there is: https://github.com/JuliaArrays/StaticArrays.jl/issues/113, which I'm waiting for!
So the other issues take priority until these are resolved...

**Comment by Benoit9** [comment]
OK, thanks! GLVisualize looks awesome, and is one of the reasons I decided to install Julia. But no rush.

**Comment by SimonDanisch** [comment]
Thanks! :) Well, it should all work on 0.5!

**Comment by sbromberger** [comment]
Just FYI, this failure is causing `PlotRecipes.jl` to fail as well. :(

**Comment by SimonDanisch** [comment]
Fun fact, Plots.jl actually halted my efforts to port GeometryTypes to StaticArrays and making it work on 0.6, because the dependencies were spread out quite far and I was running out of time ;)

**Comment by blegat** [comment]
@SimonDanisch Any update ? The two issues you mentionned earlier have now been fixed.

**Comment by SimonDanisch** [comment]
yes... it's working :D But 0.6 only because of staticarrays... I still rely quite a bit on 0.5,,, but maybe it's time to just have one working tag for 0.5 and then have a cut there!

**Comment by mkborregaard** [comment]
Not working for me? On 0.6 I have this issue even with GeometryTypes master. Is it supposed to work now?

**Comment by KristofferC** [comment]
Pretty sure https://github.com/JuliaGeometry/GeometryTypes.jl/pull/80 needs to be merged

**Comment by rdeits** [comment]
@SimonDanisch it looks like on master we no longer have `AbstractMesh <: AbstractGeometry` (which caused some minor breakage in https://github.com/rdeits/DrakeVisualizer.jl ). Do you want to restore that relationship eventually? 

One way to do it would be to change the AbstractMesh type to something like:

```julia
abstract type AbstractMesh{N, T, VertT <: StaticArray{Tuple{N}, T}, FaceT} <: AbstractGeometry{N, T}
end
```

**Comment by SimonDanisch** [comment]
The mesh type actually needs to be rewritten quite a bit for 0.6 i'd say... It still has bugs and I'm increasingly unhappy with the design. In any case, it should definitely be an AbstractGeometry ;)

**Comment by rdeits** [comment]
Ok, then I'll just work around the issue until it becomes an AbstractGeometry again.

**Comment by rdeits** [comment]
Would you be willing to tag a new release with the fix for this issue? Even if it's not fully functional on v0.6, it would be a *huge* improvement to at least have a release which can be loaded on v0.6.

**Comment by SimonDanisch** [comment]
done: https://github.com/JuliaLang/METADATA.jl/pull/9608
Now we'll need to figure out how to map from VertT to T, N in `AbstractGeometry`.

**Comment by rdeits** [comment]
Thank you!
