### ISSUE TITLE
Wrong element type when calling Vec() with heterogeneous input types

### ISSUE THREAD

**Issue by rdeits** [JuliaGeometry/GeometryTypes.jl#88]
In prior versions of GeometryTypes, `Vec(0.0, 0, 0)` would create a `Vec{3, Float64}`, but on `master` it instead creates a `Vec{1,Tuple{Float64,Int64,Int64}}`

I'll see if I can fix this.

**Comment by rdeits** [comment]
Actually, this is a StaticArrays issue. I've moved it to https://github.com/JuliaArrays/StaticArrays.jl/issues/202

**Comment by SimonDanisch** [comment]
Oh yeah sorry, we should document these kind of changes!

**Comment by SimonDanisch** [comment]
I didn't investigate, but I just took it as a given that it's a new feature of staticarrays

**Comment by rdeits** [comment]
It doesn't happen for the core StaticArrays types, so I think it's just a bug in the new FixedSizeArrays implementation:

```julia
julia> SVector(0.0, 0, 0)
3-element SVector{3,Float64}:
 0.0
 0.0
 0.0
```

**Comment by SimonDanisch** [comment]
Oh interesting :D Yeah, the port was a bit hasty
